### ISSUE TITLE
Add entry point

### ISSUE THREAD

**Issue by zariiii9003** [zhuyu4839/zlgcan-driver#9]
You could add this to you your pyproject.toml to use the [plugin interface](https://python-can.readthedocs.io/en/stable/plugin-interface.html)
```toml
[project.entry-points."can.interface"]
zlgcan = "zlgcan.zlgcan:ZCanBus"
```
Then you don't have to copy any files into the python-can directory.
